--- #YAML:1.0
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
name:         RDF-Trine
version: 0.100
author:
  - Gregory Todd Williams <gwilliams@cpan.org>
build_requires:
  Test::JSON: 0
  Test::More: 0.61
  Test::Exception: 0
recommends:
  RDF::Redland: 1
  RDF::Core: 0
requires:
    Bloom::Filter:                 0
    DBI:                           0
    DBD::SQLite:                   1.14
    Digest::MD5:                   0
    Error:                         0
    JSON:                          2
    LWP::UserAgent:                0
    List::MoreUtils:               0
    List::Util:                    0
    Math::BigInt:                  0
    Scalar::Util:                  0
    Test::More:                    0
    Unicode::Escape:               0
    URI:                           0
    XML::CommonNS:                 0.04
    XML::Namespace:                0
    XML::SAX:                      0
license: perl
distribution_type: module
generated_by: Module::Install version 0.63
no_index:
  directory:
    - inc
    - t
resources:
  homepage: http://kasei.us/code/rdf-trine/
  Repository: http://code.google.com/p/perlrdf/source
