--- #YAML:1.0
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
name:         RDF-Trine
version: 0.117
abstract: An RDF framework, providing a triplestore, parsers, serializers, and common classes for nodes, triples, quads, etc.
author:
  - Gregory Todd Williams <gwilliams@cpan.org>
build_requires:
  Test::More: 0.61
  Test::Exception: 0
  Test::JSON: 0
recommends:
  RDF::RDFa::Parser: 0.30
  RDF::Redland: 1
  RDF::Core: 0
requires:
    Data::UUID:                    0
    DBI:                           0
    DBD::SQLite:                   1.14
    Digest::MD5:                   0
    Digest::SHA1:                  0
    Error:                         0
    HTTP::Negotiate:               0
    JSON:                          2
    LWP::UserAgent:                0
    List::Util:                    0
    List::MoreUtils:               0
    Log::Log4perl:                 0
    Math::BigInt:                  0
    Math::Combinatorics:           0.09
    Scalar::Util:                  0
    Set::Scalar:                   0
    Storable:                      0
    Text::CSV:                     0
    Text::Table:                   0
    Time::HiRes:                   0
    Unicode::Escape:               0
    Unicode::String:               2.09
    URI:                           0
    XML::CommonNS:                 0.04
    XML::Namespace:                0
    XML::SAX:                      0
    XML::LibXML::SAX:              1.66
license: perl
distribution_type: module
generated_by: Module::Install version 0.63
no_index:
  directory:
    - inc
    - t
resources:
  homepage: http://kasei.us/code/rdf-trine/
  Repository: http://github.com/kasei/perlrdf/
